name: CI

em : [ push , workflow_dispatch ]
Em
empregol
    - nome : Autenticação
Em
      run : .\ngrok\ngrok.exe authtoken $Env : NGROK_AUTH_TOKEN
Em
      ambiente :
Em
        NGROK_AUTH_TOKEN : $ {{ secrets.NGROK_AUTH_TOKEN }}
Em
    - nome : Ativar TS
Em
      run : Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
Em
    - execute : Enable-NetFirewallRule -DisplayGroup "Área de Trabalho Remota"
Em
    - run : Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
Em
    - run  : Set-LocalUser -Name "TerminatorTech" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
Em
    -nome          : Criar túnel
Em
      execute  : .\n
Em
